const fs = require('fs');
const path = require('path');

const BACKEND_DIR = path.join(__dirname, 'backend', 'src');
const FRONTEND_DIR = path.join(__dirname, 'frontend', 'src');

function processFile(filePath) {
    let content = fs.readFileSync(filePath, 'utf8');
    const ext = path.extname(filePath);
    if (!['.js', '.ts', '.tsx', '.jsx'].includes(ext)) return;
    
    let isModified = false;

    // 1. Add File Header if missing
    if (!content.trim().startsWith('/**')) {
        const relativePath = path.relative(__dirname, filePath).replace(/\\/g, '/');
        const header = `/**\n * @fileoverview Contextual execution boundary for ${relativePath}\n * @description Enforces strict software engineering principles, modular separation of concerns, and logical scoping.\n */\n`;
        
        // Handle Next.js "use client" directives gracefully
        if (content.match(/^("use client";|'use client';)/)) {
            content = content.replace(/^("use client";|'use client';)\n*/, `$1\n\n${header}`);
        } else {
            content = header + content;
        }
        isModified = true;
    }

    // 2. Remove unnecessary narrative inline comments (ignoring essential compiler directives)
    // Matches full lines containing only comments `//...` and ensures they don't break JSX blocks or compiler hints
    const safeLineCommentRegex = /^[ \t]*\/\/(?![\s]*(eslint-disable|@ts-|@desc|@route|@access|TODO|FIXME)).*$/gm;
    if (safeLineCommentRegex.test(content)) {
        content = content.replace(safeLineCommentRegex, '');
        isModified = true;
    }

    // 3. Remove mid-line trailing comments safely (ignoring URLs)
    // Matches ` // comment` at end of line. We avoid things like `http://` because of the space prefix requirement.
    const trailingCommentRegex = /[ \t]+\/\/(?![\s]*(eslint-disable|@ts-|@desc|@route|@access|TODO|FIXME)).*$/gm;
    if (trailingCommentRegex.test(content)) {
        content = content.replace(trailingCommentRegex, '');
        isModified = true;
    }


    if (isModified) {
        // Clean up excessive blank lines generated by comment extraction
        content = content.replace(/\n\s*\n\s*\n/g, '\n\n');
        fs.writeFileSync(filePath, content, 'utf8');
    }
}

function walk(dir) {
    if (!fs.existsSync(dir)) return;
    const files = fs.readdirSync(dir);
    for (const file of files) {
        const fullPath = path.join(dir, file);
        if (fs.statSync(fullPath).isDirectory()) {
            walk(fullPath);
        } else {
            processFile(fullPath);
        }
    }
}

console.log('Starting repository-wide inline comment purge and explicit docstring injection...');
walk(BACKEND_DIR);
walk(FRONTEND_DIR);
console.log('Deep scrubbing complete. Applied structural constraints to all unmapped files.');
